'use client';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
import { Clock, CheckCheck, Flame, PiggyBank, TrendingUp } from 'lucide-react';
import { useApp, Panel, money, Bar as ProgressBar } from './shared';
import { localDate, type Data } from '@/lib/models';
import { financeTotals } from './finance';
export function metrics(data: Data) { const complete = data.tasks.filter(v => v.status === 'done').length; const focus = data.focus_sessions.filter(v => v.completed); const goals = data.goals.filter(v => v.progress === 100).length; const xp = complete * 10 + focus.length * 5 + goals * 100; const level = xp >= 1000 ? 4 : xp >= 400 ? 3 : xp >= 100 ? 2 : 1; return { complete, focus, goals, xp, level, levelName: ['Beginner', 'Focused', 'Productive', 'Pro Student'][level - 1], hours: focus.reduce((a, v) => a + v.duration, 0) / 3600 }; }
export function StudyChart() { const { t, data } = useApp(); const monday = new Date(); monday.setHours(0, 0, 0, 0); monday.setDate(monday.getDate() - ((monday.getDay() + 6) % 7)); const chart = Array.from({ length: 7 }, (_, i) => { const day = new Date(monday); day.setDate(day.getDate() + i); return { name: t('Дс,Сс,Ср,Бс,Жм,Сб,Жс', 'Пн,Вт,Ср,Чт,Пт,Сб,Вс').split(',')[i], hours: Number((data.focus_sessions.filter(v => v.completed && localDate(new Date(v.endedAt)) === localDate(day)).reduce((a, v) => a + v.duration, 0) / 3600).toFixed(2)) }; }); return <ResponsiveContainer width="100%" height={190}><BarChart data={chart} barSize={22} margin={{ top: 15, right: 0, left: -30, bottom: 0 }}><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="var(--border)"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 12 }}/><YAxis axisLine={false} tickLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 12 }}/><Tooltip cursor={{ fill: 'var(--muted)' }} formatter={v => [`${v} ${t('сағ', 'ч')}`, t('Оқу уақыты', 'Время учёбы')]}/><Bar dataKey="hours" fill="#8674f1" radius={[5, 5, 0, 0]}/></BarChart></ResponsiveContainer>; }
export function Analytics() { const { data, t } = useApp(); const m = metrics(data); const f = financeTotals(data); const start = new Date(); start.setHours(0, 0, 0, 0); start.setDate(start.getDate() - ((start.getDay() + 6) % 7)); const weekTasks = data.tasks.filter(v => v.status === 'done' && v.completedAt && new Date(v.completedAt) >= start).length; const weekEnd = new Date(start); weekEnd.setDate(weekEnd.getDate() + 7); const weekly = data.tasks.filter(v => new Date(v.deadline + 'T23:59:59') >= start && new Date(v.deadline + 'T00:00:00') < weekEnd); const score = weekly.length ? Math.round(weekly.filter(v => v.status === 'done').length / weekly.length * 100) : 0; return <><div className="page-heading"><div><h1>{t('Апталық аналитика', 'Недельная аналитика')}</h1><p>{t('Тұрақтылығыңды нақты сандармен көр.', 'Смотри на свою регулярность в цифрах.')}</p></div><span className="tag">{localDate(start)} — {localDate()}</span></div><div className="stat-grid">{[[Clock, t('Оқу уақыты · барлығы', 'Учёба · всё время'), m.hours.toFixed(1) + ' ' + t('сағ', 'ч')], [CheckCheck, t('Осы аптада аяқталды', 'Завершено за неделю'), weekTasks], [Flame, t('Өнімділік көрсеткіші', 'Показатель продуктивности'), score + '/100'], [PiggyBank, t('Осы айда жиналды', 'Накоплено за месяц'), money(f.saving)]].map(([I, l, v], i) => { const Icon = I as any; return <div className="stat-card" key={i}><span className="stat-icon"><Icon size={20}/></span><span className="stat-label">{l as string}</span><strong>{v as string}</strong></div>; })}</div><div className="two-grid"><Panel title={t('Осы аптадағы оқу уақыты', 'Время учёбы за неделю')} icon={TrendingUp}><StudyChart /><p className="caption">{t('Аяқталған Pomodoro сессиялары бойынша.', 'На основе завершённых сессий Pomodoro.')}</p></Panel><Panel title={t('Сенің жетістіктерің', 'Твои достижения')} icon={Flame}><div className="achievement"><span>✦</span><h2>Level {m.level} · {m.levelName}</h2><strong>{m.xp} XP</strong></div><ProgressBar value={m.level === 4 ? 100 : (m.xp - [0, 100, 400, 1000][m.level - 1]) / ([100, 400, 1000, 1000][m.level - 1] - [0, 100, 400, 1000][m.level - 1]) * 100}/><div className="analytics-lines"><p>{t('Тапсырмалар аяқталды', 'Задачи завершены')}<b>{m.complete}</b></p><p>{t('Назар сессиялары', 'Сессии фокуса')}<b>{m.focus.length}</b></p><p>{t('Мақсаттар орындалды', 'Цели достигнуты')}<b>{m.goals}</b></p></div></Panel></div><p className="caption">{t('Өнімділік: осы аптада мерзімі келетін тапсырмалардың орындалған үлесі.', 'Продуктивность: доля выполненных задач со сроком на этой неделе.')}</p></>; }
