'use client';
import { useState } from 'react';
import { CalendarDays, Flag, Search, GripVertical, Check, Plus, List, Columns3 } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useApp, Panel, Button, AddButton, Editor, Empty, DeleteButton, type Field, SelectField } from './shared';
import { localDate, type Item } from '@/lib/models';
export function useTaskEditor() { const { t, save } = useApp(); const [edit, setEdit] = useState<Item | null>(null); const fields: Field[] = [{ key: 'title', label: t('Атауы', 'Название') }, { key: 'subject', label: t('Пән', 'Предмет'), required: false }, { key: 'deadline', label: t('Мерзімі', 'Срок'), type: 'date' }, { key: 'priority', label: t('Маңыздылығы', 'Приоритет'), options: [['low', t('Төмен', 'Низкий')], ['medium', t('Орташа', 'Средний')], ['high', t('Жоғары', 'Высокий')]] }, { key: 'status', label: t('Күйі', 'Статус'), options: [['todo', t('Жоспарда', 'К выполнению')], ['progress', t('Орындалуда', 'В процессе')], ['done', t('Дайын', 'Готово')]] }, { key: 'description', label: t('Сипаттама', 'Описание'), type: 'textarea', required: false }]; return { open: (item?: Item) => setEdit(item || { id: '', title: '', subject: '', deadline: localDate(), priority: 'medium', status: 'todo', description: '' }), editor: edit && <Editor title={edit.id ? t('Тапсырманы өзгерту', 'Изменить задачу') : t('Жаңа тапсырма', 'Новая задача')} initial={edit} fields={fields} onClose={() => setEdit(null)} onSave={v => save('tasks', v, edit.id || undefined)}/> }; }
export function TaskRow({ task, onEdit }: {
    task: Item;
    onEdit: (i: Item) => void;
}) { const { t, save, busy } = useApp(); return <div className={`task-row ${task.status === 'done' ? 'completed' : ''}`}><Checkbox aria-label={t('Тапсырманы аяқтау', 'Завершить задачу')} disabled={busy} checked={task.status === 'done'} onCheckedChange={v => save('tasks', { ...task, status: v ? 'done' : 'todo' }, task.id)}/><button className="task-name" onClick={() => onEdit(task)}><strong>{task.title}</strong><span>{task.subject || t('Жеке тапсырма', 'Личная задача')}</span></button><span className={`priority ${task.priority}`}>{task.priority === 'high' ? t('Жоғары', 'Высокий') : task.priority === 'medium' ? t('Орташа', 'Средний') : t('Төмен', 'Низкий')}</span><span className={`task-date ${task.deadline < localDate() && task.status !== 'done' ? 'overdue' : ''}`}>{task.deadline.slice(5).split('-').reverse().join('.')}</span></div>; }
export function Tasks() { const { t, data, save, busy } = useApp(); const { open, editor } = useTaskEditor(); const [view, setView] = useState('board'); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const all = data.tasks.filter(v => `${v.title} ${v.subject}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || v.priority === filter)); const statuses: [
    string,
    string
][] = [['todo', t('Жоспарда', 'К выполнению')], ['progress', t('Орындалуда', 'В процессе')], ['done', t('Аяқталды', 'Завершено')]]; return <><div className="page-heading"><div><h1>{t('Тапсырмалар', 'Задачи')}<span className="count">{data.tasks.length}</span></h1><p>{t('Үлкен нәтижелер шағын қадамдардан басталады.', 'Большие результаты начинаются с маленьких шагов.')}</p></div><AddButton label={t('Тапсырма қосу', 'Добавить задачу')} onClick={() => open()}/></div><div className="toolbar"><Tabs value={view} onValueChange={setView}><TabsList><TabsTrigger value="board"><Columns3 size={15}/>Kanban</TabsTrigger><TabsTrigger value="list"><List size={15}/>{t('Тізім', 'Список')}</TabsTrigger></TabsList></Tabs><div className="row"><div className="search-box"><Search size={17}/><input aria-label={t('Іздеу', 'Поиск')} value={query} onChange={e => setQuery(e.target.value)} placeholder={t('Тапсырма іздеу…', 'Найти задачу…')}/></div><SelectField value={filter} onChange={setFilter} options={[['all', t('Барлық басымдық', 'Все приоритеты')], ['high', t('Жоғары', 'Высокий')], ['medium', t('Орташа', 'Средний')], ['low', t('Төмен', 'Низкий')]]}/></div></div>{view === 'list' ? <Panel>{all.map(task => <div key={task.id} className="list-with-delete"><TaskRow task={task} onEdit={open}/><DeleteButton table="tasks" id={task.id}/></div>)}{!all.length && <Empty text={t('Тапсырма табылмады', 'Задачи не найдены')} action={<AddButton onClick={() => open()}/>}/>}</Panel> : <div className="kanban">{statuses.map(([status, label]) => <section key={status} className={`kanban-column ${status}`} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const task = data.tasks.find(t => t.id === e.dataTransfer.getData('text/plain')); if (task && !busy)
    void save('tasks', { ...task, status }, task.id); }}><div className="kanban-head"><span className="status-dot"/><h2>{label}</h2><span className="count">{all.filter(t => t.status === status).length}</span><button className="icon-btn" onClick={() => open({ id: '', title: '', subject: '', deadline: localDate(), priority: 'medium', status, description: '' })}><Plus size={17}/></button></div>{all.filter(v => v.status === status).map(task => <article className="kanban-card" key={task.id} draggable onDragStart={e => e.dataTransfer.setData('text/plain', task.id)}><div className="row between"><span className="subject-tag">{task.subject || t('Жеке', 'Личное')}</span><GripVertical size={15} className="muted"/></div><button className="kanban-title" onClick={() => open(task)}>{task.title}</button>{task.description && <p>{task.description}</p>}<div className="row between"><span className={`priority ${task.priority}`}><Flag size={12}/>{task.priority === 'high' ? t('Жоғары', 'Высокий') : task.priority === 'medium' ? t('Орташа', 'Средний') : t('Төмен', 'Низкий')}</span><span className="caption row"><CalendarDays size={13}/>{task.deadline.slice(5)}</span></div><div className="kanban-card-footer"><SelectField value={task.status} onChange={s => save('tasks', { ...task, status: s }, task.id)} options={statuses}/><DeleteButton table="tasks" id={task.id}/></div></article>)}<button className="kanban-add" onClick={() => open({ id: '', title: '', subject: '', deadline: localDate(), priority: 'medium', status, description: '' })}><Plus size={16}/>{t('Тапсырма қосу', 'Добавить задачу')}</button></section>)}</div>}{editor}</>; }
